kind: pipeline
type: docker
name: CI/CD Frontend

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: Deploy to VPS
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: SSH_HOST
      username:
        from_secret: SSH_USERNAME
      password:
        from_secret: SSH_PASSWORD
      port: 22
      script:
        - mkdir -p ~/Document/QRApp/Frontend
        - cd ~/Document/QRApp/Frontend
        - git restore . 
        - git checkout main
        - git restore .
        - git pull origin main || true
        - make build
        - make push
        - make run