import type { OrderItem } from './card-order-item';
import CardOrderItem from './card-order-item';

export const CardOrders = () => {
  const orders: OrderItem[] = [
    {
      id: 'ORD25061501',
      status: 'pending',
      table: 'Table 12',
      area: 'Outdoor',
      customer: {
        name: 'James Wilson',
      },
      createdAt: '2023-10-01T12:30:00Z',
      totalAmount: '$45.97',
      items: [
        {
          name: 'Avocado Toast with Poached Egg',
          quantity: 1,
          price: '$12.99',
          size: 'L',
          notes: 'Extra crispy bread',
          options: [
            { option: 'Bread Type: Sourdough', price: 2.5 },
            { option: 'Egg Style: Poached', price: 4 },
          ],
        },
        {
          name: 'Fresh Orange Juice',
          quantity: 2,
          price: '$8.99',
          size: 'M',
          notes: 'No ice',
          options: [{ option: 'Size: Large', price: 2 }],
        },
        {
          name: 'Eggs Benedict',
          quantity: 1,
          price: '$15.00',
          size: 'S',
          notes: 'Hollandaise sauce on side',
          options: [
            { option: 'Bread: English Muffin', price: 1.5 },
            { option: 'Meat: Ham', price: 2 },
          ],
        },
      ],
    },
    {
      id: 'ORD25061502',
      status: 'completed',
      table: 'Table 5',
      area: 'Indoor',
      customer: { name: 'Sophia Lee' },
      createdAt: '2023-10-01T13:15:00Z',
      totalAmount: '$32.50',
      items: [
        {
          name: 'Cappuccino',
          quantity: 2,
          price: '$4.50',
          size: 'M',
          notes: 'Extra foam',
          options: [{ option: 'Milk: Whole', price: 1.5 }],
        },
        {
          name: 'Blueberry Pancakes',
          quantity: 1,
          price: '$10.00',
          size: 'L',
          notes: '',
          options: [{ option: 'Syrup: Maple', price: 2 }],
        },
        {
          name: 'Fruit Salad',
          quantity: 1,
          price: '$7.50',
          size: 'S',
          notes: 'No bananas',
          options: [{ option: 'Dressing: Honey', price: 1.5 }],
        },
      ],
    },
    {
      id: 'ORD25061503',
      status: 'pending',
      table: 'Table 8',
      area: 'Patio',
      customer: { name: 'Liam Smith' },
      createdAt: '2023-10-01T13:45:00Z',
      totalAmount: '$28.75',
      items: [
        {
          name: 'Iced Latte',
          quantity: 1,
          price: '$5.25',
          size: 'L',
          notes: 'Oat milk',
          options: [{ option: 'Sweetener: Stevia', price: 1.5 }],
        },
        {
          name: 'Veggie Omelette',
          quantity: 1,
          price: '$11.00',
          size: 'M',
          notes: 'No cheese',
          options: [{ option: 'Add-ons: Spinach', price: 1.5 }],
        },
        {
          name: 'Toast',
          quantity: 2,
          price: '$6.00',
          size: 'S',
          notes: 'Whole wheat',
          options: [{ option: 'Spread: Butter', price: 1.5 }],
        },
      ],
    },
    {
      id: 'ORD25061504',
      status: 'pending',
      table: 'Table 3',
      area: 'Indoor',
      customer: { name: 'Olivia Brown' },
      createdAt: '2023-10-01T14:10:00Z',
      totalAmount: '$22.40',
      items: [
        {
          name: 'French Toast',
          quantity: 1,
          price: '$9.00',
          size: 'M',
          notes: 'Extra syrup',
          options: [{ option: 'Topping: Berries', price: 2 }],
        },
        {
          name: 'Americano',
          quantity: 1,
          price: '$3.40',
          size: 'S',
          notes: '',
          options: [{ option: 'Milk: Skim', price: 1 }],
        },
        {
          name: 'Greek Yogurt Parfait',
          quantity: 1,
          price: '$10.00',
          size: 'L',
          notes: 'No granola',
          options: [{ option: 'Fruit: Mixed', price: 1.5 }],
        },
      ],
    },
    {
      id: 'ORD25061505',
      status: 'completed',
      table: 'Table 7',
      area: 'Outdoor',
      customer: { name: 'Noah Johnson' },
      createdAt: '2023-10-01T14:30:00Z',
      totalAmount: '$18.25',
      items: [
        {
          name: 'Espresso',
          quantity: 2,
          price: '$3.00',
          size: 'S',
          notes: '',
          options: [{ option: 'Shot: Double', price: 1 }],
        },
        {
          name: 'Bagel with Cream Cheese',
          quantity: 1,
          price: '$4.25',
          size: 'M',
          notes: 'Toasted',
          options: [{ option: 'Spread: Chive', price: 1.5 }],
        },
        {
          name: 'Apple Juice',
          quantity: 1,
          price: '$4.00',
          size: 'M',
          notes: '',
          options: [{ option: 'Ice: None', price: 0 }],
        },
      ],
    },
    {
      id: 'ORD25061506',
      status: 'pending',
      table: 'Table 2',
      area: 'Patio',
      customer: { name: 'Emma Martinez' },
      createdAt: '2023-10-01T14:45:00Z',
      totalAmount: '$27.60',
      items: [
        {
          name: 'Spinach Quiche',
          quantity: 1,
          price: '$12.00',
          size: 'L',
          notes: 'No onions',
          options: [{ option: 'Cheese: Feta', price: 2 }],
        },
        {
          name: 'Herbal Tea',
          quantity: 2,
          price: '$3.80',
          size: 'S',
          notes: 'Chamomile',
          options: [{ option: 'Honey: Yes', price: 1 }],
        },
        {
          name: 'Banana Bread',
          quantity: 1,
          price: '$6.00',
          size: 'M',
          notes: '',
          options: [{ option: 'Nuts: Walnuts', price: 1.5 }],
        },
      ],
    },
    {
      id: 'ORD25061507',
      status: 'completed',
      table: 'Table 10',
      area: 'Indoor',
      customer: { name: 'Lucas Garcia' },
      createdAt: '2023-10-01T15:00:00Z',
      totalAmount: '$35.10',
      items: [
        {
          name: 'Mocha',
          quantity: 1,
          price: '$5.50',
          size: 'L',
          notes: 'Extra chocolate',
          options: [{ option: 'Milk: Almond', price: 1.5 }],
        },
        {
          name: 'Egg White Omelette',
          quantity: 1,
          price: '$11.60',
          size: 'M',
          notes: 'No salt',
          options: [{ option: 'Veggies: Peppers', price: 1 }],
        },
        {
          name: 'Croissant',
          quantity: 2,
          price: '$8.00',
          size: 'S',
          notes: '',
          options: [{ option: 'Filling: Chocolate', price: 2 }],
        },
      ],
    },
    {
      id: 'ORD25061508',
      status: 'pending',
      table: 'Table 1',
      area: 'Outdoor',
      customer: { name: 'Mia Kim' },
      createdAt: '2023-10-01T15:20:00Z',
      totalAmount: '$19.80',
      items: [
        {
          name: 'Matcha Latte',
          quantity: 1,
          price: '$5.80',
          size: 'M',
          notes: 'Soy milk',
          options: [{ option: 'Sweetener: Agave', price: 1 }],
        },
        {
          name: 'Breakfast Burrito',
          quantity: 1,
          price: '$9.00',
          size: 'L',
          notes: 'No salsa',
          options: [{ option: 'Add-ons: Avocado', price: 2 }],
        },
        {
          name: 'Orange Scone',
          quantity: 1,
          price: '$5.00',
          size: 'S',
          notes: '',
          options: [{ option: 'Glaze: Lemon', price: 0.5 }],
        },
      ],
    },
    {
      id: 'ORD25061509',
      status: 'completed',
      table: 'Table 6',
      area: 'Patio',
      customer: { name: 'William Chen' },
      createdAt: '2023-10-01T15:40:00Z',
      totalAmount: '$24.90',
      items: [
        {
          name: 'Flat White',
          quantity: 1,
          price: '$4.90',
          size: 'M',
          notes: '',
          options: [{ option: 'Milk: Oat', price: 1 }],
        },
        {
          name: 'Egg Sandwich',
          quantity: 1,
          price: '$8.00',
          size: 'L',
          notes: 'No mayo',
          options: [{ option: 'Bread: Rye', price: 1.5 }],
        },
        {
          name: 'Fruit Cup',
          quantity: 2,
          price: '$5.00',
          size: 'S',
          notes: '',
          options: [{ option: 'Topping: Mint', price: 0.5 }],
        },
      ],
    },
    {
      id: 'ORD25061510',
      status: 'pending',
      table: 'Table 9',
      area: 'Indoor',
      customer: { name: 'Charlotte Davis' },
      createdAt: '2023-10-01T16:00:00Z',
      totalAmount: '$31.75',
      items: [
        {
          name: 'Hot Chocolate',
          quantity: 2,
          price: '$4.75',
          size: 'M',
          notes: 'Extra marshmallows',
          options: [{ option: 'Milk: Whole', price: 1 }],
        },
        {
          name: 'Belgian Waffles',
          quantity: 1,
          price: '$12.00',
          size: 'L',
          notes: 'Whipped cream',
          options: [{ option: 'Fruit: Strawberries', price: 2 }],
        },
        {
          name: 'Granola Bowl',
          quantity: 1,
          price: '$7.50',
          size: 'S',
          notes: 'No raisins',
          options: [{ option: 'Yogurt: Greek', price: 1.5 }],
        },
      ],
    },
    {
      id: 'ORD25061511',
      status: 'completed',
      table: 'Table 11',
      area: 'Outdoor',
      customer: { name: 'Benjamin Evans' },
      createdAt: '2023-10-01T16:20:00Z',
      totalAmount: '$26.30',
      items: [
        {
          name: 'Chai Latte',
          quantity: 1,
          price: '$5.30',
          size: 'M',
          notes: 'Less sweet',
          options: [{ option: 'Milk: Coconut', price: 1 }],
        },
        {
          name: 'Egg Bagel',
          quantity: 1,
          price: '$7.00',
          size: 'L',
          notes: 'No onions',
          options: [{ option: 'Spread: Herb', price: 1.5 }],
        },
        {
          name: 'Berry Muffin',
          quantity: 2,
          price: '$6.00',
          size: 'S',
          notes: '',
          options: [{ option: 'Topping: Crumble', price: 0.5 }],
        },
      ],
    },
    {
      id: 'ORD25061512',
      status: 'pending',
      table: 'Table 4',
      area: 'Patio',
      customer: { name: 'Amelia Scott' },
      createdAt: '2023-10-01T16:40:00Z',
      totalAmount: '$29.60',
      items: [
        {
          name: 'Turkish Coffee',
          quantity: 1,
          price: '$6.00',
          size: 'S',
          notes: 'No sugar',
          options: [{ option: 'Spice: Cardamom', price: 1 }],
        },
        {
          name: 'Eggs Florentine',
          quantity: 1,
          price: '$13.00',
          size: 'L',
          notes: 'Spinach on side',
          options: [{ option: 'Bread: Brioche', price: 2 }],
        },
        {
          name: 'Banana Smoothie',
          quantity: 1,
          price: '$7.60',
          size: 'M',
          notes: 'No dairy',
          options: [{ option: 'Milk: Almond', price: 1.5 }],
        },
      ],
    },
  ];
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 pb-14">
      {orders.map((order) => (
        <CardOrderItem key={order.id} order={order} />
      ))}
    </div>
  );
};
export default CardOrders;
